# Generated by Django 4.0.5 on 2024-11-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='serial_motor',
            field=models.CharField(default='No disponible', max_length=50),
        ),
    ]
